# Netlify Configuration for Coiffeur Platform

[build]
  # Build command and publish directory
  command = "pnpm install && pnpm build"
  publish = "apps/web/.next"
  functions = "netlify/functions"

[build.environment]
  # Node version for builds
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # prevent Netlify npm install
  NETLIFY_USE_PNPM = "true"

  # Enable Next.js optimizations
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Production context
[context.production]
  command = "pnpm install && pnpm build"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://coiffeur-platform.ch"

# Staging/branch deploy context
[context.branch-deploy]
  command = "pnpm install && pnpm build"

[context.branch-deploy.environment]
  NODE_ENV = "staging"
  NEXT_PUBLIC_SITE_URL = "https://$BRANCH.coiffeur-platform.netlify.app"

# Preview context for pull requests
[context.deploy-preview]
  command = "pnpm install && pnpm build"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--coiffeur-platform.netlify.app"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.coiffeur-platform.ch/*"
  to = "https://coiffeur-platform.ch/:splat"
  status = 301
  force = true

# Force HTTPS
[[redirects]]
  from = "http://coiffeur-platform.ch/*"
  to = "https://coiffeur-platform.ch/:splat"
  status = 301
  force = true

# SPA fallback for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.stripe.com https://*.sumup.com https://www.googletagmanager.com https://*.sentry.io;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' data: blob: https://*.supabase.co https://*.stripe.com;
      connect-src 'self' https://*.supabase.co https://*.stripe.com https://*.sumup.com https://*.sentry.io wss://*.supabase.co;
      frame-src 'self' https://*.stripe.com https://*.sumup.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """

# API headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image caching
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=31536000"

# Font caching
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions."*"]
    external_node_modules = ["@supabase/supabase-js", "stripe"]

# Forms (for contact forms, etc.)
[forms]
  honeypot = true

# Plugins configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variable validation
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Dev settings for local testing
[dev]
  command = "pnpm dev"
  port = 3000
  targetPort = 3000
  publish = "apps/web/.next"
  autoLaunch = false